language: python
python:
  - 3.8
services:
  - postgresql
cache:
  directories:
    - $HOME/.cache/pip
  before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
    - rm -rf $HOME/.cache/pip/http
install:
  - pip install -r backend/requirements.txt
before_script:
  - touch backend/local_settings.py
  - psql -c 'create database scrumsistant;' -U postgres
  - echo "FLASK_SECRET_KEY=b'11111111111111111111111111111111';REDIS_CONNECTION_URL='redis://:trash@trash:5555/0';POSTGRES_URL='postgres://postgres:@localhost:5432/scrumsistant';SERVER_NAME='me';" > backend/local_settings.py
  - sed -i -n 's/django:.*\@/postgres:@/p' backend/alembic.ini
  - alembic upgrade head
script:
  - pytest --cov=scrumsistant backend/tests
after_success:
  - coveralls
