env:
  global:
    - TEST=true
language: python
python: 
  - 3.8
install:
  - pip install -r backend/requirements.txt
before_script:
  - touch backend/local_settings.py
  - echo "FLASK_SECRET_KEY=b'red';REDIS_CONNECTION_URL='redis://:trash@trash:5555/0'" > backend/local_settings.py
script:
  - pytest --cov=scrumsistant backend/tests
after_success:
  - coveralls
