language: python
python:
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
  before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
    - rm -rf $HOME/.cache/pip/http
install:
  - pip install -r backend/requirements.txt
before_script:
  - touch backend/local_settings.py
  - echo "FLASK_SECRET_KEY=b'11111111111111111111111111111111';REDIS_CONNECTION_URL='redis://:trash@trash:5555/0';SERVER_NAME='me';" > backend/local_settings.py
script:
  - pytest --cov=scrumsistant backend/tests
after_success:
  - coveralls
