version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  flask:
    build:
      context: .
      dockerfile: Dockerfile_Flask
    command: bash -c "flask run"
    ports:
      - "5000:5000"
    depends_on:
      - redis
  websocket:
    build:
      context: .
      dockerfile: Dockerfile_Websocket
    command: bash -c "python runserver.py"
    depends_on:
      - redis
  angular:
    build:
      context: .
      dockerfile: Dockerfile_Angular
    command: bash -c "node_modules/bin/ng serve"
    ports:
      - "4200:4200"
    depends_on:
      - redis
      - websocket
      - flask
