name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: lint
      run: |
        pylint backend/ --exit-zero
    - name: test
      run: |
        coverage run -m pytest backend/
    - name: coverage
      run: |
        coverage report -m

